#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Dec  1 17:26:12 2022

Stage: Development-01

@author: tahamertkirmizgul-120202009
@author: yagızuygun-119202075
@author: ayhanemreşermet-117202098
"""


import requests
from bs4 import BeautifulSoup

url = 'https://www.imdb.com/chart/top/'
page = requests.get(url)
soup = BeautifulSoup(page.content, "html.parser")


